global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: telegram
    telegram_configs:
      - bot_token:   "8350074658:AAGJ8Vw-DLqtYEouAcZoafnFmmmS5PhPoiU"
        chat_id:     -1002808461142
        parse_mode:  Markdown
        message: |
          {{ range .Alerts }}
          🚨 *Alert:* {{ .Annotations.summary }}
          • *Name:* {{ .Labels.alertname }}
          • *Severity:* {{ .Labels.severity }}
          • *Instance:* {{ .Labels.instance }}
          • *Time:* {{ .StartsAt }}
          {{ end }}
