global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["server:8000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
